version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beauteria
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: beauteria_db
    restart: always
    environment:
      MYSQL_DATABASE: beauteria
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
